// <auto-generated />
using System;
using Employees;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employees.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1991, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeedBy = "Juno",
                            Name = "Stuart Bradley"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeedBy = "Blackpool Sixth Form",
                            Name = "Amy Jones"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1972, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeedBy = "National Savings",
                            Name = "Marianne Bradley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
